### ISSUE TITLE
Credential in the plugin

### ISSUE THREAD

**Issue by gbin** [KenMercusLai/err-vdo#3]
Just to let you know that you might have leaked credentials in this plugin:
https://github.com/KenMercusLai/err-vdo/blob/master/vdo.py#L72

**Comment by KenMercusLai** [comment]
Thanks. 

Is there any practical way to use my user/password in the file and remove it when git it in?

**Comment by gbin** [comment]
yes, you can make a new file and add its path relative to the root of the project to your .gitignore so it won't be considered for addition in the repo.

See for example config.py from the bot itself: https://github.com/errbotio/errbot/blob/master/.gitignore#L6

**Comment by KenMercusLai** [comment]
thanks, helps a lot
